spring:
  datasource:
    url: jdbc:mysql://localhost:3306/protect_animal?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html

spring.mvc:
  static-path-pattern: /static/**
  view:
    prefix: /
    suffix: .jsp

server:
  port: 8099
